# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 상지디앤씨
short_title: 
email: sangjidc@hanmail.net
description: > # this means to ignore newlines until "baseurl:"
  상지디앤씨는 우리의 더 나은 삶을 디자인하는 공간 설계 스튜디오입니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
facebook_username: SPACE4-275414592487427
instagram_username: spacefor
pinterest_username: SPACE4FOR
address: 서울특별시 서초구 강남대로 23길 90, 2층(양재동)
phone_number : 02-453-9060~3
fax_number : 02-453-9064

# Build settings
markdown: kramdown
